[toolchain]

[features]
resolution = true
skip-lint = false

[workspace]
members = ["programs/mica_eur"]

[programs.localnet]
mica_eur = "9x3tkUkajECAgPvS59YTAdD7VZRMRckrPxFC4MZspup5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --ignore tests/jest/**/*.ts tests/**/*.ts"

[dependencies]
proc-macro2 = "=1.0.94"
