name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run linter
        run: npm run lint

      - name: Fast build (skip BPF)
        run: npm run build:fast

      - name: Verify TypeScript types
        run: npm run verify:types

      - name: Verify signature handling
        run: npm run verify:signatures

      - name: Run pre-commit test suite
        run: npm run test:precommit 