name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 24.x
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run linter
        run: npm run lint

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libssl-dev curl

      - name: Setup Solana CLI
        run:
          sh -c "$(curl -sSfL https://release.anza.xyz/v1.18.17/install)"
          
      - name: Setup local environment
        run: bash scripts/setup.sh --rust --anchor --env --keys

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Fast build (skip BPF)
        run: npm run build:fast

      - name: Verify TypeScript types
        run: npm run verify:types

      - name: Verify signature handling
        run: npm run verify:signatures

      - name: Run pre-commit test suite
        run: npm run test:precommit 
